export const mapProjects = [
    {id: 1, location: "Laredo", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 2, location: "Donosti", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)" },
    {id: 3, location: "Mungia", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 4, location: "Bilbao", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 5, location: "Erandio", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)" },
    {id: 6, location: "Bilbao", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 7, location: "Sondika", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 8, location: "Arrankudiaga", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 9, location: "Tacoronte, Tenerife", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 10, location: "Comillas", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 11, location: "Bilbao", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 12, location: "Bermeo", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 13, location: "Gatika", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 14, location: "Butroi", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 15, location: "Mungia", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 16, location: "Gorliz", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 17, location: "Getxo", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 18, location: "Bermeo", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 19, location: "Bilbao", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 20, location: "Las Arenas", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 21, location: "Bilbao", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 22, location: "Gijon", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 23, location: "Gatika", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 24, location: "Bilbao", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 25, location: "Bilbao", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 26, location: "Durango", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 27, location: "Deusto", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 28, location: "Mungia", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 29, location: "Etxebarri", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 30, location: "Durango", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 31, location: "Bermeo", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 32, location: "Bakio", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 33, location: "Bilbao", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    {id: 34, location: "Bilbao", type: {es: "Proyecto", eu: "Proiektua", en: "Project"}, color: "var(--dark-color)"},
    
    {id: 35, location: "Donosti", type: {es: "Gestión", eu: "Kudeaketa", en: "Management"}, color: "var(--orange-color)"},
    {id: 36, location: "Tudela", type: {es: "Gestión", eu: "Kudeaketa", en: "Management"}, color: "var(--orange-color)"},
    {id: 37, location: "Bilbao", type: {es: "Gestión", eu: "Kudeaketa", en: "Management"}, color: "var(--orange-color)"},
    {id: 38, location: "Bilbao", type: {es: "Gestión", eu: "Kudeaketa", en: "Management"}, color: "var(--orange-color)"},
    {id: 39, location: "Barcelona", type: {es: "Gestión", eu: "Kudeaketa", en: "Management"}, color: "var(--orange-color)"},
    {id: 40, location: "Madrid", type: {es: "Gestión", eu: "Kudeaketa", en: "Management"}, color: "var(--orange-color)"},
    {id: 41, location: "Mallorca", type: {es: "Gestión", eu: "Kudeaketa", en: "Management"}, color: "var(--orange-color)"},
    {id: 42, location: "Zaragoza", type: {es: "Gestión", eu: "Kudeaketa", en: "Management"}, color: "var(--orange-color)"},
]